spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.92.132:9092
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
author:
  name: xiajw
  birth: 1995
