spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.92.132:9092
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
author:
  name: xiajw.testBus
  birth: 1995
