spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiajw2018/springcloudconfig.git
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 8081
